# Generated by Django 6.0.3 on 2026-04-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course_name',
            field=models.CharField(choices=[('algorithms', 'Основы алгоритмизации и программирования'), ('web_design', 'Основы веб-дизайна'), ('database_design', 'Основы проектирования баз данных')], max_length=100, verbose_name='Наименование курса'),
        ),
    ]
